version: "3.8"
services:
  backend:
    build: .
    container_name: pingme-backend
    env_file: .env.docker
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    networks:
      - pingme-network
    command: npx nodemon index.js
    working_dir: /app
  frontend:
    build:
      context: ../FRONTEND/pingMe
    container_name: pingme-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - pingme-network
volumes:
  mongo_data:

networks:
  pingme-network:
    driver: bridge